### ISSUE TITLE
RBDOOM-3-BFG VR Linux

### ISSUE THREAD

**Issue by serk7** [Codes4Fun/RBDOOM-3-BFG#83]
I managed to compile it on linux but i get a segmentation error at launch. Are you going to work to support it on linux? Is it possible to help some how?

----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 1.10.0
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();

**Comment by Codes4Fun** [comment]
I'd like to get it working but reading the pages on SteamVR support sounds
like it's still very limited. It says in the readme that opengl
applications run to slow to be interactive. Another issue is that it says
you can't display both on the desktop and hmd, but it's not clear what that
means since doom 3 does this itself, so I wonder if they mean SteamVR can't
do it or if there is an issues with applications doing it themselves. So it
sounds like this early version of SteamVR is only targeting certain
application.

On Feb 25, 2017 2:18 AM, "serk7" <notifications@github.com> wrote:

I managed to compile it on linux but i get a segmentation error at launch.
Are you going to work to support it on linux? Is it possible to help some
how?

----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 1.10.0
signal caught: Segmentation fault
si_code 1
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop();

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Codes4Fun/RBDOOM-3-BFG/issues/83>, or mute the thread

**Comment by serk7** [comment]
I dont know, but all aplications i tested it's replied on screen, like in windows.

But yep, you are right, the actual steam vr on linux is really alpha state, I have huge delay at moving and many issues. I hope see some improvements soon. 

Thank you for the reply.

**Comment by ChristophHaag** [comment]
On my RX 480 with radv, performance and reprojection is both bad/broken, and as the SteamVR readme says, all OpenGL rendering will not be optimal yet, but it does compile and run just fine.

![screenshot_20170305_135536](https://cloud.githubusercontent.com/assets/781076/23587406/8169463e-01ab-11e7-8c1e-f7fc8ea85954.png)

**Comment by Seegras** [comment]
I also get a segfault. Here's the backtrace:

#0  _dl_close (_map=0x0) at dl-close.c:817
#1  0x00007ffff7de84f4 in _dl_catch_error (objname=0x5555586cdfa0, 
    errstring=0x5555586cdfa8, mallocedp=0x5555586cdf98, 
    operate=0x7ffff4ad8fb0 <dlclose_doit>, args=0x0) at dl-error.c:187
#2  0x00007ffff4ad9521 in _dlerror_run (
    operate=operate@entry=0x7ffff4ad8fb0 <dlclose_doit>, args=0x0)
    at dlerror.c:163
#3  0x00007ffff4ad8fdf in __dlclose (handle=<optimized out>) at dlclose.c:46
#4  0x00007ffff4ce1c2b in vr::VR_InitInternal (
    peError=peError@entry=0x7fffffffce30, 
    eApplicationType=eApplicationType@entry=vr::VRApplication_Scene)
    at openvr_api.cpp:46
#5  0x0000555555907f35 in vr::VR_Init (
    eApplicationType=vr::VRApplication_Scene, peError=<synthetic pointer>)
    at RBDOOM-3-BFG/neo/libs/openvr/headers/openvr.h:3324
#6  VR_Init ()
    at RBDOOM-3-BFG/neo/renderer/RenderSystem_init.cpp:853
#7  R_InitOpenGL ()
    at RBDOOM-3-BFG/neo/renderer/RenderSystem_init.cpp:950
#8  0x0000555555908fc9 in idRenderSystemLocal::InitOpenGL (
    this=<optimized out>)
    at RBDOOM-3-BFG/neo/renderer/RenderSystem_init.cpp:3160
#9  0x00005555557de3b9 in idCommonLocal::Init (
---Type <return> to continue, or q <return> to quit---
    this=0x555556403c20 <commonLocal>, argc=<optimized out>, 
    argv=<optimized out>, cmdline=<optimized out>)
    at RBDOOM-3-BFG/neo/framework/Common.cpp:1269
#10 0x000055555579636b in main (argc=1, argv=0x7fffffffda98)
    at RBDOOM-3-BFG/neo/sys/posix/platform_linux.cpp:537

**Comment by serk7** [comment]
Ye, will be nice if you tell us how you managed to make it run!

**Comment by serk7** [comment]
Btw, looking your screenshoot seems is not direct mode... when i make screenshot the view of my headset doesnt appear on it like a secondary monitor.

**Comment by ChristophHaag** [comment]
I can't say I did anything special. In neo/ I did cmake; make and then ./RBDoom3BFG. Of course with the game files in the right place (I don't know where that is, I set that up with the original RBDoom3BFG a long time ago, somewhere in my home directory).

It's not direct mode because there is no direct mode for AMD GPUs on Linux. Valve recently hired Keith Packard as consultant and he'll make sure it comes to AMD GPUs too.

Edit: Forgot to mention that I'm on a very up to date Archlinux, so either it's "extended mode" or a bleeding edge system that makes it work.

**Comment by serk7** [comment]
oh, i didn't know that. I compiled it in a diferent way.. i will try again. Thank you anyway.

**Comment by serk7** [comment]
nvm, keep crashing, doesnt matter how i compile it :(

WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
Couldn't open journal files
/proc/cpuinfo CPU processors: 3
/proc/cpuinfo CPU logical cores: 3
execing default.cfg
couldn't exec D3BFGVRConfig.cfg
couldn't exec autoexec.cfg
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 1.10.0
signal caught: Segmentation fault

**Comment by ChristophHaag** [comment]
Hm...
```
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
/proc/cpuinfo CPU processors: 3
/proc/cpuinfo CPU logical cores: 3
execing default.cfg
execing D3BFGVRConfig.cfg
couldn't exec autoexec.cfg
----- R_InitOpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Using GLEW 1.10.0
/home/chris/.local/share/Steam/SteamApps/common/SteamVR/tools/bin/linux64/vrdashboard: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
GameController 0 name: XInput Controller
GameController 0 is mapped as "00000000000000000000000000000000,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,".
OpenGL Version   : 3.0
OpenGL Vendor    : X.Org
OpenGL Renderer  : Gallium 0.4 on AMD POLARIS10 (DRM 3.9.0 / 4.10.0-g4977ab6e92e2, LLVM 5.0.0)
OpenGL GLSL      : 1.3
```
etc.

I looked it up and under ~/.rbdoom3bfg I have a symlink base -> ~/SteamApps/common/DOOM 3 BFG Edition/base/. But that's probably not the cause anyway, when the stacktrace ends at

```
vr::VR_InitInternal (
peError=peError@entry=0x7fffffffce30,
eApplicationType=eApplicationType@entry=vr::VRApplication_Scene)
at openvr_api.cpp:46
```
This sounds more like something going wrong in SteamVR.

**Comment by sherlok235** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
guillaumerioux, @dominik77, @altunmehmetedu, @Yamboy1, @JulietaLudmila, @winker57, @pucek1000, @exababy0, @gfbsenol444, @GeoArgy, @M4cs, @Kedjik3, @Seanhooper1, @DiggerLbC, @sane5ek, @lucylow, @JustTofex, @fearlessmaniak, @Yasar1987, @gorkemeyler
